LOCAL_PATH := $(call my-dir)

OPENSSL_SRC_FILES := \


OPENSSL_INCLUDE_FILES := $(LOCAL_PATH)/openssl/include

include $(CLEAR_VARS)

LOCAL_MODULE := openssl
LOCAL_C_INCLUDES:= $(OPENSSL_INCLUDE_FILES)
LOCAL_SRC_FILES := $(OPENSSL_SRC_FILES)

include $(BUILD_SHARED_LIBRARY)
